### ISSUE TITLE
Multiple Sources

### ISSUE THREAD

**Issue by phrfpeixoto** [flaviostutz/rtsp-relay#3]
Hi!

Is it possible to allow query arguments to be passed to the source stream?
My use case is a DVR appliance that takes a camera as a query arg on the RTSP query:

`rtsp://user:pass@IP:554/H264?ch=??`

So it would be nice if I could do `rtsp://localhost:8554/stream?ch=12`

**Comment by flaviostutz** [comment]
Have you tried to use those query params directly in the source url?

Something like
SOURCE_URL=http://93.87.72.254:8090/mjpg/video.mjpg?resolution=low

**Comment by phrfpeixoto** [comment]
Hi! Thanks for replying.

Yes, it works perfectly on the `SOURCE_URL`. That I mean here is that there are some arguments that I want to "expose", IE the channel number.

**Comment by flaviostutz** [comment]
Hm... so when you request a feed (a new client subscribes the feed) it would append this argument to the source feed, right?

With current architecture this is not possible because we are more a repeater than a proxy. To do that we would have to change lots of things.

For now, you could create various containers, each pointing to a channel in source-URL and exposing a different port on the host, so that if one want to access ch3, point to rtsp://host:1103, if wants to access ch15, point to rtsp://host:1115 and so on.

The footprint of this container is minimal, so launching 20 instances in a Raspberry would not be a trouble.

Hope this helps you.
